---
output: github_document
editor_options:
  markdown:
    wrap:      80
    canonical: false
---

```{r config}
#| echo: false

REPOSITORY_NAME <- "mirt-parameters"
GITHUB_USERNAME <- "DaniMori"
AUTHOR_NAME     <- "Daniel Morillo"
GITHUB_OWNER    <- GITHUB_USERNAME

# Objects created automatically (no need to edit)

## Repository configuration objects
profile_url     <- paste0("https://github.com/", GITHUB_OWNER)
repo_url        <- paste(profile_url, REPOSITORY_NAME, sep = '/')
https_clone_url <- paste0(repo_url, '.git')
creation_year   <- lubridate::now() |> lubridate::year()

## Software version objects
r_version     <- paste(version$major, version$minor, sep = '.')
rs_version    <- rstudioapi::versionInfo()$long_version
rs_version_dl <- rs_version |> stringr::str_replace('\\+', '-')
q_version     <- quarto::quarto_version()
git_version   <- gitr::git_version()
```

# Repository ``r REPOSITORY_NAME``

Paper "A generalized definition of multidimensional item response
theory parameters"

# License

<!-- TODO: Choose a license and update this section, if necessary -->

[Repository `r REPOSITORY_NAME`](`r repo_url`) © `r creation_year` by
[`r AUTHOR_NAME`](`r profile_url`) is licensed under [CC BY 4.0][license].
Please see the [license file][licfile].

[license]: https://creativecommons.org/licenses/by/4.0

[licfile]: LICENSE.md

## Attributions

### Rstudio project template

This project makes use of the [rproj-template][selflink] Github template
created by [Daniel Morillo][profile] and licensed under the 
[Creative Commons Attribution 4.0 International license][repo_lic].

[selflink]: https://github.com/DaniMori/rproj-template

[profile]: https://github.com/DaniMori

[repo_lic]: https://creativecommons.org/licenses/by/4.0

<!-- TODO: Add attributions to other software components, if necessary -->

### <Software component>

# Project installation

## Software components

Start by installing the following software components:

- [R version `r r_version`][R]:
  In Windows, using the [binary installer][inst] is recommended.

[R]: https://cran.rstudio.com/bin/windows/base/old/`r r_version`/
[inst]: https://cran.rstudio.com/bin/windows/base/old/`r r_version`/R-`r r_version`-win.exe

- [Rstudio Desktop][RS]: Although not strictly necessary, it is recommended
  to install the Rstudio IDE; for strict reproducibility, use build
  [`r rs_version` for Windows 10/11][RSv].

[RS]: https://posit.co/download/rstudio-desktop/

[RSv]: https://download1.rstudio.org/electron/windows/RStudio-`r rs_version_dl`.exe

- [Quarto publishing system][Q]: An additional component used by Rstudio to
generate and publish literate computing outputs. For strict reproducibility
please use build `r q_version`; On Windows, use [the 64-bit installer][QW].

[Q]: https://quarto.org/

[QW]: https://github.com/quarto-dev/quarto-cli/releases/download/v`r q_version`/quarto-`r q_version`-win.msi

- [Git client][G]: Install the Git client in order to be able to clone locally
  the project repository.
  On Windows, use [the 64-bit Windows installer][GW].

[G]: https://git-scm.com/download

[GW]: https://github.com/git-for-windows/git/releases/download/v`r git_version`.windows.1/Git-`r git_version`-64-bit.exe

## Installing the project locally

This project is hosted as a GitHub repository.
It can be cloned as a local Git repository following [these instructions][CR]
(steps 2 through 7).
Note that this will create a local copy of ('clone') the GitHub repository as an
Rstudio project in the folder specified.
The URL that must be entered into the `Repository URL` text box is:

```
`r https_clone_url`
```

[CR]: https://book.cds101.com/using-rstudio-server-to-clone-a-github-repo-as-a-new-project.html#step---2

**IMPORTANT:** It is totally unrecommended to clone a git repository inside a
cloud storage folder (e.g., Dropbox, OneDrive). Please note that GitHub serves
the purpose of backing up the repository, so no cloud storage is necessary.
Similarly, cloning the repository in a network folder may cause problems with
the `renv` environment (see below); do it at your own risk!

After cloning the repository,
the Rstudio project will open automatically in the Rstudio IDE.
If it doesn't, or you want to return later to the project in Rstudio,
you can do so by double clicking on the file `rstudio_project.Rproj`
that has been created in the project folder when cloning the repository.

**NOTE:** It is common practice to avoid using and versioning `.Rprofile` files.
However, this project uses [package `renv`][renv]
to create a reproducible environment,
which needs the `.Rprofile` file that lives in the root directory of the
project. **Please DO NOT delete or edit this file**; it will install and
activate the `renv` package and make it ready for restoring the environment.

[renv]: https://cran.r-project.org/package=renv

## Restoring the environment

The reproducible environment created by `renv` must be restored to install all
the packages this project needs to be built properly. If `renv` does not
initialize automatically (check the console for messages about this), you will
need to manually install the package first:

```r
install.packages("renv")
```

Once it is successfully installed, use the "renv" -\> "Restore library..."
button in Rstudio's "Packages" tab to restore the environment. Alternatively,
you can type in the console:

```r         
renv::restore(prompt = FALSE)
```

# Repository structure

The file structure of this repository is as follows:

```
`r REPOSITORY_NAME`
|
|--- apps         (To store apps, e.g. in Shiny)
|
|--- dat          (To store input datasets; must NEVER be checked-in to Github)
|
|--- doc          (To store important documentation of the project)
|    |
|    |--- minutes (To store meeting minutes)
|
|--- notebooks    (Notebooks to explore data and test processes live here)
|
|--- output       (Processing outputs; files must be individually "checked-in"
|                 when necessary)
|
|--- R            (R functions created for this project live here)
|
|--- renv         (System library necesssary for `renv` to work. DON'T TOUCH)
|
|--- src          (Source scripts that implement the main processes)
|
|--- www          (Project assets, e.g., images, bibliography files, etc.)
```

Use the folders as indicated to store the different files and generate the
outputs of the processes.

# How to use this project

## Main output

The main file is
[`output/paper_draft/paper_M2PLM_parameters.Rmd`][paper],
which renders the article main text output.

[paper]: output/paper_draft/paper_M2PLM_parameters.Rmd

The output of this file is the document that will eventually
be submitted to a journal,
along with the necessary additional files (i.e., cover letter).
If the rendering is successful, the output will be generated in file
"output/Main_text.docx".

**NOTE:** When opening the output document,
Word will prompt to "Update the fields".
This is [set by design in the R package `officer`][update_prompt],
used to render the document, for security reasons.
It is enough to click on "Yes" in the pop-up window.

[update_prompt]: https://ardata-fr.github.io/officeverse/faq.html#update-fields

## Rendering the output

A script for building the project is provided in file
[`src/Build_project.R`](src/Build_project.R).
The easiest way to render the output is by sourcing this script, running the
following command:

```r
source("src/Build_project.R", encoding = 'UTF-8')
```

The output file generated will be in the following path:

```
"output/Main_text.docx"
```

**NOTE:** Rendering the project may take a while, especially the first time.
This is due to the `renv` package restoring the environment, which implies
downloading and installing several R packages. Please, be patient!
