---
output:
  officedown::rdocx_document:
    mapstyles:
      First Paragraph: Body Text
    base_format: bookdown::word_document2
    reference_docx: ../www/Template.docx
    number_sections: no
    keep_md:         no
editor_options: 
  chunk_output_type: console
---

**Article title:**
A Generalized Definition of Multidimensional Item Response Theory Parameters

**Running title:** Generalized MIRT parameters

# List of authors

- Daniel Morillo-Cuadrado. Department of Behavioral Science Methodology,
  Faculty of Psychology, Universidad Nacional de Educación a Distancia (UNED),
  Spain.
  
- Mario Luzardo-Verde. Department of Mathematics and Applications,
  Universidad de La República, Uruguay.

## Corresponding author:

Daniel Morillo-Cuadrado \
Faculty of Psychology, Office 2.74. \
C. de Juan del Rosal 10, 28040 Madrid

Phone nº: +34 91398 6584 \
Email address: dvmorillo@psi.uned.es

# Acknowledgements

The authors would like to thank:
[Patricia Recio-Saboya, Ph.D.](https://orcid.org/0000-0002-0530-4404),
for her valuable guidance regarding multidimensional estimation
in IRT software packages;
[Jay Verkuilen, Ph.D.,](https://orcid.org/0000-0003-3546-3411),
for his comments and suggestions regarding covariance whitening;
David Thissen and three additional anonymous reviewers for
their valuable comments and suggestions of early drafts of this manuscript.

# Data Availability Statement

All the materials and code of this paper are available as
a Software Heritage repository, under the following SWHID persistent identifier:

[swh:1:dir:3914435e67a2b34847e36a712a181d7d9d76f35e;origin=https://github.com/DaniMori/mirt-parameters;visit=swh:1:snp:9069b256471ea08d5748e8bb021b7ee876aee724;anchor=swh:1:rev:fe49f438bf940606ae7e3c86c3c55f202e6920af](https://archive.softwareheritage.org/swh:1:dir:3914435e67a2b34847e36a712a181d7d9d76f35e;origin=https://github.com/DaniMori/mirt-parameters;visit=swh:1:snp:9069b256471ea08d5748e8bb021b7ee876aee724;anchor=swh:1:rev:fe49f438bf940606ae7e3c86c3c55f202e6920af)

# Financial Support

This research received no specific grant funding form any funding agency,
commercial or not-for-profit sectors.

# Competing Interests Statement

Competing interests: The authors declare none.
